model:
  type: "RandomForestClassifier"
  path: "saved_models/random_forest_model.pkl"
  features_path: "saved_models/model_features.txt"
  n_estimators: 200
  max_depth: 10
  min_samples_leaf: 10
  class_weight: "balanced"